name: Deploy to AWS

on: [push, pull_request]


jobs:   
  deploy_test_image:
    runs-on: ubuntu-latest    
    steps:
      - name: log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cryptoapi:test
  
  run_test:
    needs: deploy_test_image
    runs-on: ubuntu-latest
    
    services:
      mock_api:
        image: huyhoangio/cryptoapi:test
        credentials:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        env:
          COINBASE_SPOT_ENDPOINT: https://api.coinbase.com/v2/prices/spot?currency=        
        ports:
          - 5000:5000
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
    
      - name: run test file
        run: |
          pip install requests
          pip install pytest
          pytest test_app.py
  
  deploy_prod_image:
    needs: run_test
    runs-on: ubuntu-latest

    steps:
      - name: log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cryptoapi:latest
      